name: Actualizar fecha y hora en main

on:
  schedule:
    - cron: '0 15 * * *'    # 10:00 AM Perú (15:00 UTC)
    - cron: '30 20 * * *'   # 3:30 PM Perú (20:30 UTC)
    - cron: '0 0 * * *'     # 7:00 PM Perú (00:00 UTC)
  workflow_dispatch:

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar acceso al repositorio
        run: |
          gh repo view JunalChowdhuryGomez/date-update
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_JUNALCHOWDHURYG }}

      - name: Clonar el repositorio
        uses: actions/checkout@v3
        with:
          repository: JunalChowdhuryGomez/date-update
          token: ${{ secrets.PAT_JUNALCHOWDHURYG }}
          ref: main  # Especifica la rama predeterminada

      - name: Configurar Git
        run: |
          git config user.name "JunalChowdhuryG"
          git config user.email "chowdhurygomezjunaljohir@gmail.com"

      - name: Actualizar fecha.txt con fecha y hora Perú
        run: |
          TZ='America/Lima' date '+%d/%m/%Y %H:%M:%S' >> fecha.txt

      - name: Hacer commit y push a main
        run: |
          git add fecha.txt
          git commit -m "Actualizar fecha y hora automáticamente" || echo "No hay cambios para cometer"
          git push origin main